### ISSUE TITLE
ServiceMonitor (for prometheus operator)

### ISSUE THREAD

**Issue by leogr** [vchain-us/kube-notary#11]
In order to make kube-notary discovered by the prometheus operator:

- the endpoint resource needs the following label:
```yaml
  labels:
    k8s-app: kube-notary
```

- the ServiceMonitor resource has to be created, as following:
```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-notary
spec:
  endpoints:
  - interval: 15s
    port: metrics-port
  selector:
    matchLabels:
      k8s-app: kube-notary
```

TODOs:
- for a unknown reason, the `app.kubernetes.io/*` seem to do not work (need investigation)
- the required label could be set in the default setup
- this configuration should be added to the repo
