### ISSUE TITLE
OpenShift - no kube-notary metrics show up in Prometheus

### ISSUE THREAD

**Issue by vchain-us-mgmt** [vchain-us/kube-notary#13]
I deployed Kube-Notary using the kubernetes templates as described in issue [12](https://github.com/vchain-us/kube-notary/issues/12) but couldn't find any image status metrics. Prometheus finds no targets to scrape Kube-Notary.

The Prometheus configuration is default without any changes.

**Comment by vchain-us-mgmt** [comment]
found it - there is no scraping configuration for Pods by default. Editing the Prometheus configmap (kubectl edit configmap prometheus -n kube-system) and adding the following job fixed it:

```
    - job_name: 'kubernetes-pods'
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

```
