### ISSUE TITLE
image verification fails: Authentication is required

### ISSUE THREAD

**Issue by dzlabsch** [vchain-us/kube-notary#25]
Kube-Notary is manually deployed into my K8s environment, but I noticed some errors in my pod log:

`time="2020-04-10T06:27:19Z" level=error msg="Cannot verify \"docker-pullable://...: Authentication is required"`

It's a private image registry - how can I enable the kube-notary to check these images as well?

**Comment by dzlabsch** [comment]
found and fixed the issue as follows:

1) create a secret in the kube-notary namespace (or the namespaces kube-notary pods are running) containing the container registry access credentials

`kubectl create secret docker-registry regcred --docker-server=<registry-url> --docker-username=<registry-username> --docker-password=<registry-password> --docker-email=<registry-email>`

2) change the kube-notary deployment to add the registry access:

```
      imagePullSecrets:
      - name: regcred
```

The complete deployment looks like that:

```
---
# Source: kube-notary/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-notary
  labels:
    app.kubernetes.io/name: kube-notary
    app.kubernetes.io/instance: kube-notary
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-notary
      app.kubernetes.io/instance: kube-notary
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-notary
        app.kubernetes.io/instance: kube-notary
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '9581'
    spec:
      serviceAccountName: kube-notary
      volumes:
        - name: config-volume
          configMap:
            name: kube-notary
      containers:
        - name: kube-notary
          image: "codenotary/kube-notary:latest"
          imagePullPolicy: Always
          imagePullSecrets:
          - name: regcred
          volumeMounts:
          - name: config-volume
            mountPath: /etc/kube-notary
          ports:
          - containerPort: 9581
            name: metrics-port
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics-port
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics-port
          resources:
            {}
```

**Comment by vchain-us-mgmt** [comment]
if you run an older Kubernetes version, you might get an error like:
`# * : Invalid value: "The edited file failed validation": ValidationError(Deployment.spec.template.spec.containers[0]): unknown field "imagePullSecrets" in io.k8s.api.core.v1.Container
`

In that case you need to place the imagePullSecrets section differently:

```
apiVersion: extensions/v1beta1
...

    spec:
      containers:
      - image: codenotary/kube-notary:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kube-notary
        ports:
        - containerPort: 9581
          name: metrics-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics-port
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/kube-notary
          name: config-volume
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: regcred
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-notary
        name: config-volume
```
